paths:
  /api/product/delete:
    delete:
      summary: Delete a product
      tags: [Product]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteProductDTO"
      responses:
        "200":
          description: Product deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: Product not found or unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
