paths:
  /api/user/product/:
    get:
      summary: Get all products By user id with pagination
      tags: [Product]
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          description: Page number (default is 1)
          schema:
            type: integer
        - name: limit
          in: query
          description: Number of items per page (default is 10)
          schema:
            type: integer
      responses:
        "200":
          description: User's products retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PeginationProductResponse"
        "400":
          description: No products found for this user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
