paths:
  /api/product:
    get:
      summary: Get all products with pagination
      tags: [Product]
      parameters:
        - name: page
          in: query
          description: Page number (default is 1)
          schema:
            type: integer
        - name: limit
          in: query
          description: Number of items per page (default is 5)
          schema:
            type: integer
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PeginationProductResponse"
        "400":
          description: Bad request or no products found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
