paths:
  /api/product/update:
    put:
      summary: Update an existing product
      tags: [Product]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductDTO'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Validation error or product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
