paths:
  /api/category/create:
    post:
      summary: Create a new category
      tags: [Category]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCategoryDTO"
      responses:
        "201":
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: Validation error or category exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
