paths:
  /api/user/category/{categoryId}:
    delete:
      summary: Delete a category
      tags: [Category]
      security:
        - BearerAuth: []
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Category deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: Category not found or unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
