paths:
  /api/category/delete:
    delete:
      summary: Delete a category
      tags: [Category]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteCategoryDTO"
      responses:
        "200":
          description: Category deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: Category not found or unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
