paths:
  /api/user/me:
    delete:
      summary: Delete current user account
      tags: [User]
      security:
        - BearerAuth: []
      responses:
        200:
          description: Account deleted and session cleared
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        401:
          description: Unauthorized
