paths:
  /api/auth/logout:
    post:
      summary: Logout current user
      tags: [Auth]
      security:
        - BearerAuth: []
      responses:
        200:
          description: Logout successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        401:
          description: Bad Request
