paths:
  /api/auth/verify-email:
    get:
      summary: Verify email using OTP code
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyEmailDTO"
      responses:
        200:
          description: Email verified successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        400:
          description: Invalid or expired verification code
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
